### PR TITLE
Adding prettier/updating eslint

### PR DESCRIPTION
**Pull request by haxxxton**
This change introduces prettier, and reduces the complexity of the eslint file

In order to preserve only formatted files ending up in each commit, added husky to check precommits for any unformatted files and bail if they dont pass linting

This PR also includes the addition of a package.json file that includes the devDependencies to facilitate the above

~~Most notable yuckiness is that this highlights that our script files have no way of checking what global variables are available. As a temporary work around for this preventing development, i have hushed the eslint rule for `no-undef` until we can either find a way to import the vtt globals from somewhere, add them to the eslint file as declared globals, or potentially switch to typescript and define them with `declare`.~~

### CODE REVIEW

**Comment by Dulux-Oz** [comment]
If we're talking about the same thing:

There's a "global" variable (object) viewable from the "F12-console" which contains an awful lot of stuff, including a "game" sub-object which in turn contains a "deadlands_classic" sub-object which we create as part of the initialization process of the game-system (see the fpCreateNamespace() function in the dlc-main.js file).

Or am I barking up the wrong (object) tree.  :-P

**Comment by haxxxton** [comment]
@Dulux-Oz Yeah, those are globals im talking about. (listed in the [docs](https://foundryvtt.com/api/modules/client.html)). What I'd like to be able to have is the _code_ know about those globals. I am looking at what i can automate in terms of extraction from the servers public folder (which includes the `foundry.js` and `commons.js` files). This might allow me to either generate an eslint config that lists all the known globals from foundry, or potentially allow us to "import" these globals from a single file that just reexports them. Its mostly to make development faster, so we can identify typos/known global values.

I know there is a `globalThis` value that is available for most things, but the docs arent the most comprehensive in terms of what gets stored directly upon this object, or nested within a deeper value (as well as being available globally)

**Comment by Dulux-Oz** [comment]
Sorry, so you're talking ENV=dev, not ENV=prod (ie end-user) stuff. I see. I don't know, there's a hell of a lot of stuff / code / etc there; finding it all (I imagine) is going to be a b!tch!

(And that's the end of my input to this topic, except as replies to others' ideas :-(  )

**Comment by haxxxton** [comment]
@Dulux-Oz , I have managed to add the extracted global classes, functions, and variables. These then extend the base eslint config to define them as globals

**Review by Dulux-Oz — APPROVED** [review]
Looks OK to me

**Review by TheSpyder — APPROVED** [review]
It's plausible we'll need TypeScript at some point, but the foundry extension system seems to work via loading the project straight from git - so we'd need to check in the compiled JS which I'm not usually a fan of.

**Pull request merged**
