### PR TITLE
Define items 

### PR DESCRIPTION
**Pull request by Ampersandrew**
These changes allow the creation, editing and viewing of all the items needed for the three settings.

These are the game items in the sidebar, not yet attached to any given character.

Still to do, but probbaly not in this task:
1) Allow physical items (four types) to be added to a character and have them shown on the sheet. 
2) Make the tweakable specifics of the item editable on the character sheet, i.e. quantity, price and notes.

3) Allow adding and configuring edges and hindrances
4) Decide what to do with spelllike edges — hexes, blessings, etc.
5) Decide how to handle money, probably another item type.

### CODE REVIEW

**Comment by TheSpyder** [comment]
I've had a play with it on my server now, just working my way through code review.

I'm a little surprised things like the list of edges and hinderances aren't pre-defined?

**Comment by Ampersandrew** [comment]
Well, I keep seeing experienced developers tell people who want to import a list of stuff into Foundry, that they'd be much better off using Foundry to define those items and them add them to a compendium.

I'm also wary of putting copyright material in a publicly accessible online location. What we chose to do on our own computers is our business, until we distribute it, or make it available. That moves firmly out of the fair use arena.

As it is, for testing this, I define a couple of items and make sure the code is handling them correctly. When this is mostly complete, we'll likely put it on a publicly inaccessible server and input the data we need.

The next change, that I haven't added yet, because you have enough to look at here, lets you add and delete items on a character. 

Next step after that is handling edges and hindrances.

**Review by TheSpyder — APPROVED** [review]

**Comment by TheSpyder** [comment]
> Well, I keep seeing experienced developers tell people who want to import a list of stuff into Foundry, that they'd be much better off using Foundry to define those items and them add them to a compendium.

That sounds like something I haven't explored yet. I assumed each new campaign would be a new world generated from the game system - is that not true? or is the "compendium" a way to pre-fill the base data for a world?


> I'm also wary of putting copyright material in a publicly accessible online location. What we chose to do on our own computers is our business, until we distribute it, or make it available. That moves firmly out of the fair use arena.

Oh oops, yeah for sure that is a good idea!

**Comment by TheSpyder** [comment]
> is the "compendium" a way to pre-fill the base data for a world?

I need to google before I submit comments 🙃 

https://foundryvtt.com/article/compendium/

**Pull request merged**
